### ISSUE TITLE
Need installation instructions for Windows dependencies

### ISSUE THREAD

**Issue by DashW** [gabrieleilertsen/lumahdrv#1]
Optional libraries such as OpenExr, Matroska, PFS and EBML are not mentioned in the Readme. Rather than requiring the developer to trawl through the CMake files for information, the ideal installation locations (include/ and lib/ directories) should be listed.

**Comment by gabrieleilertsen** [comment]
Under 'Compilation and installation', the dependencies of Luma HDRv are listed. VPX, Matroska and EBML are required, but are compiled together with the Luma HDRv libraries if not found on the system. OpenEXR is required to compile encoding and decoding applications, but PFS is optional.

**Comment by DashW** [comment]
Is a specific version of OpenEXR required? 

What about GLEW and GLUT for the player application? (GLUT has been deprecated for quite some time!) Is FreeGLUT compatible?

EDIT: Just tried compiling with OpenEXR version 2.2.0, and was confronted with a few missing symbols including Imf::RgbaInputFile and Imf::GlobalThreadCount, so I presume OpenEXR version 2.2.0 is not compatible.

**Comment by gabrieleilertsen** [comment]
No, the 2.2 versions of OpenEXR should all be ok. I have used both 2.2.0 and 2.2.1. I guess you have encountered some Windows specific issue again.

For GLEW, I'm using versions 1.13.0. I have not tried the 2.X versions, but I assume these should be ok as well. And yes, FreeGLUT is compatible. I'm using FreeGLUT 3.0.0, which seems to be the latest version.
