### ISSUE TITLE
Failed to locate Luma HDRv meta data in '01_hevc_sumsung.mkv'

### ISSUE THREAD

**Issue by Hans1984** [gabrieleilertsen/lumahdrv#2]
Hi, thanks for the useful tools. However, I found some problems, when I tried to use the test sample. 
 
I'm sure the input video is HDR video which is encoded  by HEVC, but it shows the error 'Failed to locate Luma HDRv meta data in '01_hevc_sumsung.mkv'.

Could anyone tell me what the problem is?
So many thanks.

**Comment by DashW** [comment]
Luma is a custom codec, and the Luma decoder can only work with videos encoded by the Luma encoder with its non-standard metadata. I believe videos encoded with any other encoder cannot be decoded by Luma.

**Comment by Hans1984** [comment]
@DashW 
Thanks! And do you know other software that can decode the standard HDR video file（HDR 10 or DV），because I want to get some HDR frames from the Video.
Thank again!

**Comment by DashW** [comment]
Good question, I haven't tried it myself but I'm told pfstools can do the job: 
http://pfstools.sourceforge.net/

Or, if you don't mind capturing LDR frames, the latest version of VLC Player now supports HDR video playback:
https://www.vlchelp.com/take-picture-snapshot-video/
